services:
  - type: web
    name: living-entradasya
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://living.entradasya.cl
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: LIVING_ADMIN_USER
        sync: false
      - key: LIVING_ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: MP_PUBLIC_KEY
        sync: false
